name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Find and Build All Rust Projects
        run: |
          for dir in Rust_basic/Lesson_1/*/ ; do
            if [ -f "$dir/Cargo.toml" ]; then
              echo "Building project in $dir"
              (cd "$dir" && cargo build --verbose)
            fi
          done
      - name: Find and Test All Rust Projects
        run: |
          for dir in Rust_basic/Lesson_1/*/ ; do
            if [ -f "$dir/Cargo.toml" ]; then
              echo "Running tests in $dir"
              (cd "$dir" && cargo test --verbose)
            fi
          done
