name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Compile Rust Programs
        run: |
          for file in $(find . -name "*.rs"); do
            echo "Compiling $file"
            rustc "$file" -o "${file%.rs}.out"
          done

      - name: Run Compiled Programs
        run: |
          for exec in $(find . -name "*.out"); do
            echo "Running $exec"
            $exec
          done
